name: ontheway-home
favicon: null
layout_spectrum: 0.763518457999453
typography_spectrum: 0.627339277183637
title: 'short and long stories  '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a36c6a'
    - '#b58a8b'
    - '#694952'
    - '#1e1110'
    - '#e4c599'
  brandStrength: 0.5625
  lightness: 0.625
  saturation: 0.4375
  rhythmicContrast: 0.25
purpose: []
