name: ontheway-home
favicon: null
layout_spectrum: 0.763518457999453
typography_spectrum: 0.627339277183637
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1e2221'
    - '#10100e'
    - '#30383b'
    - '#535353'
    - '#837666'
  brandStrength: 0.5
  lightness: 0.7548720762133598
  saturation: 0.8336369178723544
  rhythmicContrast: 0.19401405192911625
purpose: []
